version: '3'
services:
  web21:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - 3000:3000  # expose port to public this time - in dev no nginx is used
