name: Build docker images and push them to GitHub registry

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image and push it
        uses: docker/build-push-action@v1
        with:
          repository: dccnconf/web25
          tag_with_ref: true
          tags: latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
